### ISSUE TITLE
Force-Closes on KitKat

### ISSUE THREAD

**Issue by ghost** [guardianproject/notecipher#24]
Not much to add, "report" button has been clicked ;-)

**Comment by eighthave** [comment]
Looks like this is the backtrace, perhaps updating SQLCipher to v3.0 will fix this.  Its some kind of missing C++ name-mangling issue (that stuff is such a pain...)

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN7android10MemoryBaseC1ERKNS_2spINS_11IMemoryHeapEEElj" referenced by "libdatabase_sqlcipher.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:364)
at java.lang.System.loadLibrary(System.java:526)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:144)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:137)
at info.guardianproject.notepadbot.NoteCipher.onCreate(NoteCipher.java:93)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by uberspot** [comment]
This looks related to this https://dev.guardianproject.info/issues/2884 
I also remember testing the latest upstream (with the updated sqlcipher) on 4.4.2 and it didn't have this problem. If it persists after the update let me know. :)

**Comment by ghost** [comment]
When will this fix be released to the android store? The current version (0.0.7.1) is from September 11, 2013...

**Comment by uberspot** [comment]
#28 has to be fixed first and then it can be released.
