### ISSUE TITLE
RuntimeException: Unable to resume activity

### ISSUE THREAD

**Issue by eighthave** [guardianproject/notecipher#26]
There have been 42 of these reported:

```
java.lang.RuntimeException: Unable to resume activity {info.guardianproject.notepadbot/info.guardianproject.notepadbot.NoteEdit}: java.lang.IllegalStateException: trying to requery an already closed cursor net.sqlcipher.CrossProcessCursorWrapper@426b5850
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2793)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5168)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: trying to requery an already closed cursor net.sqlcipher.CrossProcessCursorWrapper@426b5850
at android.app.Activity.performRestart(Activity.java:5247)
at android.app.Activity.performResume(Activity.java:5270)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2754)
... 10 more
```

Here are some comments:
- crash when sharing note via gmail
- again crash...over over time crasinhg wish u luck to trobleshooting that bug...ha a nice Day www.twitter.com/Bocarte | about.me/pollakkamil ADD ME ALL I WANT BE CONNECT WITH U SEEYA LATER
- note cypher has stoppedworking lg g2 e every time!!
- Crash: Multitask, Reopen. Note10.1 gtn8000 4.1.2
- I was copy pasting to Notecipher
- Stopped when phone came out of standby
- program stop every time screen locks
- just running
- when the screen shuts off you crash
- o programa para sempre que eu saiu dele e tento voltar

**Comment by Akshaypure** [comment]
If you are using method startManagingCursor(cursor)..remove it. Manage cursor mutually.
